/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Gratheon",
  "tagline": "Dinosaurs are cool",
  "favicon": "favicons/favicon.ico",
  "url": "https://gratheon.com",
  "baseUrl": "/",
  "organizationName": "gratheon",
  "projectName": "website",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "presets": [
    [
      "classic",
      {
        "gtag": {
          "trackingID": "GTM-KH4KC9",
          "anonymizeIP": true
        },
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/gratheon/website/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "blog": {
          "blogSidebarCount": 20,
          "showLastUpdateTime": false,
          "blogSidebarTitle": " ",
          "showReadingTime": true,
          "postsPerPage": 20,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "editUrl": "https://github.com/gratheon/website/tree/main/",
          "onInlineTags": "warn",
          "onInlineAuthors": "warn",
          "onUntruncatedBlogPosts": "warn"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "pages": {
          "path": "./pages",
          "routeBasePath": "",
          "include": [
            "**/*.{js,jsx,ts,tsx,md,mdx}"
          ],
          "exclude": [
            "**/_*.{js,jsx,ts,tsx,md,mdx}",
            "**/_*/**",
            "**/*.test.{js,jsx,ts,tsx}",
            "**/__tests__/**"
          ],
          "mdxPageComponent": "@theme/MDXPage",
          "rehypePlugins": [],
          "beforeDefaultRemarkPlugins": [],
          "beforeDefaultRehypePlugins": []
        }
      }
    ]
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "image": "img/gratheon-web-app.webp",
    "navbar": {
      "title": "",
      "logo": {
        "alt": "Gratheon",
        "src": "img/logo_v7w.svg"
      },
      "items": [
        {
          "to": "/about",
          "label": "About",
          "position": "left"
        },
        {
          "to": "/about/products",
          "label": "Products",
          "position": "left"
        },
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Docs"
        },
        {
          "to": "/research",
          "label": "Research",
          "position": "left",
          "sidebarId": "researchSidebar"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "to": "/pricing",
          "label": "Pricing",
          "position": "left"
        },
        {
          "type": "search",
          "position": "right"
        },
        {
          "aria-label": "Discord Invite",
          "className": "navbar--discord-link",
          "href": "https://discord.gg/PcbP4uedWj",
          "position": "right"
        },
        {
          "href": "https://github.com/gratheon/web-app",
          "position": "right",
          "className": "header--github-link",
          "aria-label": "GitHub repository"
        },
        {
          "href": "https://app.gratheon.com/account/authenticate/",
          "label": "Log in",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "items": [
            {
              "html": "\n                <a href=\"https://ariregister.rik.ee/est/company/12245103/Gratheon-O%C3%9C\">Gratheon OÜ</a><br />\n                Tallinn, Estonia\n              "
            }
          ],
          "title": null
        },
        {
          "items": [
            {
              "label": "Privacy Policy",
              "to": "privacy"
            },
            {
              "label": "Terms Of Service",
              "to": "terms"
            },
            {
              "label": "Email",
              "href": "mailto:pilot@gratheon.com"
            }
          ],
          "title": null
        },
        {
          "items": [
            {
              "label": "Telegram",
              "href": "https://t.me/gratheon"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/gratheon"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/company/gratheon/"
            }
          ],
          "title": null
        },
        {
          "items": [
            {
              "label": "Facebook",
              "to": "https://www.facebook.com/gratheon"
            },
            {
              "label": "Twitch",
              "to": "https://www.twitch.tv/tot_ra"
            },
            {
              "label": "Youtube",
              "href": "https://www.youtube.com/@gratheon-bees"
            }
          ],
          "title": null
        },
        {
          "items": [
            {
              "html": "<img src=\"/img/nvidia-inception-program-badge-rgb-for-screen.svg\" alt=\"NVIDIA Inception Program Member\" style=\"max-width:200px; height: auto;\" />"
            }
          ],
          "title": null
        }
      ]
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "api",
        "path": "./about",
        "routeBasePath": "about",
        "sidebarPath": "sidebars.ts"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "research",
        "path": "./research",
        "routeBasePath": "research",
        "sidebarPath": "sidebars.research.ts"
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
